baseURL = "https://pdp.dev/"
languageCode = "en-us"
publishDir = "public"
pygmentsUseClasses = true
pygmentsCodefences = true
theme = "pdp80-theme"
title = "Phil Piwonka"
[params]
	author = "Phil Piwonka"
	email = "hello@pdp.dev"
	bio = ""
	description = "yea hi"
	enableRSS = true
	facebook = "phil.piwonka"
	subtitle404 = ""
	title404 = ""
[markup.goldmark.renderer]
    unsafe= true
