baseURL = "https://pdp.dev/"
languageCode = "en-us"
publishDir = "public"
pygmentsUseClasses = true
pygmentsCodefences = true
theme = "pdp80-theme"
title = "Phil Piwonka"
enableRobotsTXT = false
[params]
	author = "Phil Piwonka"
	description = "This is Phil Piwonka's blog for writing whatevs"
	email = "hello@pdp.dev"
	bio = ""
	enableRSS = true
	subtitle404 = ""
	title404 = ""
	ogtitle = "https://pdp.dev/images/hey-arcade.jpeg"
[markup.goldmark.renderer]
    unsafe= true
