baseURL = "https://pdp80.com/"
languageCode = "en-us"
title = "Phil Piwonka"
theme = "temple"

[params]
  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  # topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "blog/:year/:month/:slug"

[author]
  name = "Phil Piwonka"
  github = "wnka"
  gaid = "UA-21053678-2"
  twitter = "wnka"