baseURL = "https://pdp80.com/"
languageCode = "en-us"
title = "Phil Piwonka"
theme = "pdp80-theme"
pygmentsUseClasses=true

[params]
	author = "Phil Piwonka"
	description = "yea hi"
	bio = ""

	twitter = "wnka"
	facebook = "phil.piwonka"

	enableRSS = true

	# 404 page
	title404 = ""
	subtitle404 = ""
